version: "3.9"

services:
  recipes.webapi:
    image: ${DOCKER_REGISTRY-}recipeswebapi
    ports:
      - "3000:3000"  
    build:
      context: .
      dockerfile: Recipes.WebApi/Dockerfile
    mem_limit: 700m  
    cpus: 1.0
    restart: always  
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=RecipesDB;User=sa;Password=YourStrong@Passw0rd;Encrypt=True;TrustServerCertificate=True; 
    depends_on:
      - mssql
    volumes:
      - recipes_storage:/app/Recipes.Infrastructure/Storage 

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
  recipes_storage: